### ISSUE TITLE
 not 	compatible with ffi 2.0.1.

### ISSUE THREAD

**Issue by yyccR** [am15h/tflite_flutter_helper#65]
Hope to be compatible with the ffi 2.x version

**Comment by ChangJoo-Park** [comment]
+1

**Comment by Guynullin** [comment]
edit pubspec.yaml in flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/tflite_flutter_helper-0.3.1
to: 
  ffi: ^2.0.1

but I also used this solution to make the plugin work with flutter 3

        @sircambridge you can try

      url: https://github.com/elephantum/tflite_flutter_helper.git
      ref: a7d7a59a33f7cffa0a2a12ab05625807622cc97a

_Originally posted by @elephantum in https://github.com/am15h/tflite_flutter_helper/issues/57#issuecomment-1133103451_
      
so I first copied the corrected repository to the plugin folder

Then you can try the flutter clean followed by the flutter pub get.

**Comment by espbee** [comment]
Are there plans to update this lib more formally? Would be vastly appreciated.

**Comment by charlieforward9** [comment]
This is resolved on: 

```yaml 
tflite_flutter_helper:
  git:
    url: https://github.com/VisualPT/tflite_flutter_helper.git
    ref: 627abb6f41e2fa4949ccf64226009c06e7021308
```
