### ISSUE TITLE
A value of type 'ImageData?' can't be assigned to a variable of type 'List<int>?'. Try changing the type of the variable, or casting the right-hand type to 'List<int>?'

### ISSUE THREAD

**Issue by nugaysamil** [am15h/tflite_flutter_helper#75]
![Screen Shot 2023-11-10 at 17 16 37](https://github.com/am15h/tflite_flutter_helper/assets/106466382/67f41b39-04cf-4c39-be26-b95f69c85f7e)

How can I fix this error?

**Comment by charlieforward9** [comment]
Pretty that's because of a dependency mismatch. I fixed this on my fork of this repo.

```yaml 
tflite_flutter_helper:
  git:
    url: https://github.com/VisualPT/tflite_flutter_helper.git
    ref: 627abb6f41e2fa4949ccf64226009c06e7021308
```
