### ISSUE TITLE
 TensorBuffer.createFixedSize is not supported.

### ISSUE THREAD

**Issue by HarshKevadiya2403** [am15h/tflite_flutter_helper#79]
Error: Member not found: 'float32'.
    final output = TensorBuffer.createFixedSize([1, 128], TfLiteType.float32);

I'm using the tflite_flutter_helper_plus package to work with TensorFlow Lite models in my Flutter app. When I try to create a TensorBuffer using TensorBuffer.createFixedSize([1, 160, 160, 3], TfLiteType.float32), I get the following error: "Error: Unsupported feature: TensorBuffer.createFixedSize is not supported."

I have the tflite_flutter package installed and have verified that I'm using the latest version of both packages.

![image](https://github.com/user-attachments/assets/ca0bba4f-8965-4de5-81af-7ca4db16c5fe)

**Comment by charlieforward9** [comment]
`TfLiteTypes` are now called `TensorType`. I have this fix on my fork.

```yaml 
tflite_flutter_helper:
  git:
    url: https://github.com/VisualPT/tflite_flutter_helper.git
    ref: 627abb6f41e2fa4949ccf64226009c06e7021308
```
